### ISSUE TITLE
How to build OrkTrack and OrkWeb?

### ISSUE THREAD

**Issue by uj** [voiceip/oreka#32]
The main page mentions the improvements to OrkTrack and OrkWeb and OrkAudio, but it only gives build instructions for OrkAudio.  Are there updated instructions on building OrkTrack and OrkWeb?

**Comment by kingster** [comment]
Both `OrkTrack` and `OrkWeb` are now maven packages, so just running `mvn clean install` / `mvn clean package` would build the war files that you need.

Let me know if you still face any issue.

**Comment by uj** [comment]
Ok, so I did as you said, and here is where I'm getting stuck now:

`[INFO] Reactor Summary:

[INFO]

[INFO] orkbasej ........................................... SUCCESS [  4.860 s]

[INFO] orktrack ........................................... FAILURE [  1.471 s]

[INFO] orekaj-parent ...................................... SKIPPED

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 6.531 s

[INFO] Finished at: 2020-11-09T19:54:38-05:00

[INFO] Final Memory: 21M/64M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project orktrack: Compilation failure

[ERROR] /root/oreka-master/orktrack/src/main/java/net/sf/oreka/orktrack/LogManager.java:[76,20] cannot access org.apache.logging.log4j.spi.LoggerContextShutdownEnabled

[ERROR] class file for org.apache.logging.log4j.spi.LoggerContextShutdownEnabled not found
`

**Comment by kingster** [comment]
Hi

Looks like the build broke sometime due to dependency issue. This is fixed via #34 

Can you please test with the latest version. Travis runs now reports that java modules are [building properly](https://travis-ci.com/github/voiceip/oreka/jobs/432136194)

Please reopen the issue if you are still facing issue.

**Comment by kingster** [comment]
Have also published the binaries in the latest release https://github.com/voiceip/oreka/releases/tag/v0.2.2

**Comment by uj** [comment]
Thank you for the binaries, I will use those.

I tried running the mvn install again with your new changes, and it now fails at the tests.  It says it can't find certain files at C:\..... but this is linux (Ubuntu 16.04) so of course there is no "C:\" drive.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.sf.oreka.orktrack.test.PortTest
2020-11-10 18:53:29,916 ERROR  [main] OrkTrack.initialize: Error configuring Hibernate:Log4j properties file does not exist:C:/oreka/orktrack/log4j.properties check your web.xml
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.799 sec <<< FAILURE! - in net.sf.oreka.orktrack.test.PortTest
testTapeAndMetadataMessage(net.sf.oreka.orktrack.test.PortTest)  Time elapsed: 0.753 sec  <<< ERROR!
net.sf.oreka.OrkException: Log4j properties file does not exist:C:/oreka/orktrack/log4j.properties check your web.xml
        at net.sf.oreka.orktrack.LogManager.configure(LogManager.java:80)
        at net.sf.oreka.orktrack.LogManager.configure(LogManager.java:63)
        at net.sf.oreka.orktrack.OrkTrack.initialize(OrkTrack.java:47)
        at net.sf.oreka.orktrack.test.PortTest.setUp(PortTest.java:46)

Running net.sf.oreka.orktrack.test.ProgramTest
2020-11-10 18:53:29,950 ERROR  [main] OrkTrack.initialize: Error configuring Hibernate:Log4j properties file does not exist:C:/oreka/orktrack/log4j.properties check your web.xml
2020-11-10 18:53:29,958 ERROR  [main] OrkTrack.initialize: Error configuring Hibernate:Log4j properties file does not exist:C:/oreka/orktrack/log4j.properties check your web.xml
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in net.sf.oreka.orktrack.test.ProgramTest
testSchedule(net.sf.oreka.orktrack.test.ProgramTest)  Time elapsed: 0 sec  <<< ERROR!
net.sf.oreka.OrkException: Log4j properties file does not exist:C:/oreka/orktrack/log4j.properties check your web.xml
        at net.sf.oreka.orktrack.LogManager.configure(LogManager.java:80)
        at net.sf.oreka.orktrack.LogManager.configure(LogManager.java:63)
        at net.sf.oreka.orktrack.OrkTrack.initialize(OrkTrack.java:47)
        at net.sf.oreka.orktrack.test.ProgramTest.setUp(ProgramTest.java:42)

test1(net.sf.oreka.orktrack.test.ProgramTest)  Time elapsed: 0 sec  <<< ERROR!
net.sf.oreka.OrkException: Log4j properties file does not exist:C:/oreka/orktrack/log4j.properties check your web.xml
        at net.sf.oreka.orktrack.LogManager.configure(LogManager.java:80)
        at net.sf.oreka.orktrack.LogManager.configure(LogManager.java:63)
        at net.sf.oreka.orktrack.OrkTrack.initialize(OrkTrack.java:47)
        at net.sf.oreka.orktrack.test.ProgramTest.setUp(ProgramTest.java:42)


Results :

Tests in error:
  PortTest.setUp:46 » Ork Log4j properties file does not exist:C:/oreka/orktrack...
  ProgramTest.setUp:42 » Ork Log4j properties file does not exist:C:/oreka/orktr...
  ProgramTest.setUp:42 » Ork Log4j properties file does not exist:C:/oreka/orktr...

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0
```

**Comment by kingster** [comment]
You need to run with skipTests, as this package tests are very old and don't run on Linux systems! 

`mvn clean install -DskipTests=true` is the command that is used by Travis to generate the binaries.
