### ISSUE TITLE
Orkweb and Orktrack

### ISSUE THREAD

**Issue by NelsonBA81** [voiceip/oreka#56]
Hello,

For some reason, I can't have both tomcat apps working, both of them are giving these errors on orkweb.log:
`
2021-07-16 18:02:18,465 DEBUG Environment [http-nio-8080-exec-205] HHH000206: hibernate.properties not found
2021-07-16 18:02:18,554 DEBUG JaxbCfgProcessor [http-nio-8080-exec-205] cfg.xml document did not define namespaces; wrapping in custom event reader to introduce namespace information
2021-07-16 18:02:18,655 ERROR  [http-nio-8080-exec-205] OrkTrack.initialize: Error configuring Hibernate:Unable to perform unmarshalling at line number 0 and column 0 in FILE /etc/oreka/database.hbm.xml. Message: null
2021-07-16 18:02:18,655 ERROR  [http-nio-8080-exec-205] OrkTrack ContextInitialized() threw exception
org.hibernate.internal.util.config.ConfigurationException: Unable to perform unmarshalling at line number 0 and column 0 in FILE /etc/oreka/database.hbm.xml. Message: null
        at org.hibernate.boot.cfgxml.internal.JaxbCfgProcessor.unmarshal(JaxbCfgProcessor.java:133) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
        at org.hibernate.boot.cfgxml.internal.JaxbCfgProcessor.unmarshal(JaxbCfgProcessor.java:65) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
        at org.hibernate.boot.cfgxml.internal.ConfigLoader.loadConfigXmlFile(ConfigLoader.java:76) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
        at org.hibernate.boot.registry.StandardServiceRegistryBuilder.configure(StandardServiceRegistryBuilder.java:238) ~[hibernate-core-5.4.15.Final.jar:5.4.15.Final]
`

Can you please provide some help here?
about the /etc/oreka/database.hbm.xml config file, I've this:
`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hibernate-configuration PUBLIC
                "-//Hibernate/Hibernate Configuration DTD 3.0//EN"
                "http://hibernate.sourceforge.net/hibernate-configuration-3.0.dtd">

<hibernate-configuration>

    <session-factory>
        <property name="hibernate.dialect">org.hibernate.dialect.MySQL55Dialect</property>
        <property name="hibernate.connection.maxconnections">256</property>
        <property name="hibernate.connection.driver_class">com.mysql.cj.jdbc.Driver</property>
        <property name="hibernate.connection.url">jdbc:mysql://localhost/oreka?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=WEST</property>
        <property name="hibernate.connection.password">password</property>
        <property name="hibernate.connection.username">user</property>

        <property name="hibernate.hbm2ddl.auto">update</property> 
        <property name="hibernate.show_sql">true</property>

        <property name="hibernate.jdbc.use_scrollable_resultset">true</property>
        <property name="hibernate.max_fetch_depth">1</property>
        <property name="hibernate.cache.provider_class">org.hibernate.cache.HashtableCacheProvider</property>
    </session-factory>

</hibernate-configuration>
`

thank you and
Best Regards,
Nelson

**Comment by kingster** [comment]
This config file is invalid. Please follow the installation guide at https://github.com/voiceip/oreka/wiki/Installation

Sample database [database.hbm.xml](https://github.com/voiceip/oreka/blob/master/orkbasej/src/resources/database.hbm.xml)

**Comment by NelsonBA81** [comment]
Hello,

I'm sorry for my mistake in pasting the config file, but github formatted the text in wrong way, here is the config file that we have:
#Begining of the file
```

<?xml version="1.0" encoding="UTF-8"?>

<hibernate-configuration>

    <session-factory>
        <property name="hibernate.dialect">org.hibernate.dialect.MySQL55Dialect</property>
        <property name="hibernate.connection.maxconnections">256</property>
        <property name="hibernate.connection.driver_class">com.mysql.cj.jdbc.Driver</property>
        <property name="hibernate.connection.url">jdbc:mysql://localhost/oreka?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=WEST</property>
        <property name="hibernate.connection.password">password</property>
        <property name="hibernate.connection.username">user</property>

        <property name="hibernate.hbm2ddl.auto">update</property> <!-- update, create, create-drop -->
        <property name="hibernate.show_sql">true</property>

        <property name="hibernate.jdbc.use_scrollable_resultset">true</property>
        <property name="hibernate.max_fetch_depth">1</property>
        <property name="hibernate.cache.provider_class">org.hibernate.cache.HashtableCacheProvider</property>
    </session-factory>

</hibernate-configuration>


```
#End of File

Thank you and 
Best regards,
Nelson

**Comment by kingster** [comment]
Can you please share the complete stacks trace of the error ?

**Comment by kingster** [comment]
Which version of tomcat & java are you running? Also, are you directly using the release war or are you building from source?

**Comment by kingster** [comment]
Also, can you follow the steps here https://hibernate.atlassian.net/browse/HHH-13381. Try encoding the `&` chars.
